// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from common.proto</summary>
public static partial class CommonReflection {

  #region Descriptor
  /// <summary>File descriptor for common.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CommonReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cgxjb21tb24ucHJvdG8ibgoKUGxheWVySW5mbxIOCgZyb2xlSWQYASABKAMS",
          "DAoEbmljaxgCIAEoCRILCgNzZXgYAyABKAUSDgoGaGVhZElkGAQgASgFEgoK",
          "Amx2GAUgASgFEgwKBGdvbGQYBiABKAUSCwoDZXhwGAcgASgFYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PlayerInfo), global::PlayerInfo.Parser, new[]{ "RoleId", "Nick", "Sex", "HeadId", "Lv", "Gold", "Exp" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
///玩家角色结构体，基础信息
/// </summary>
public sealed partial class PlayerInfo :IProto , pb::IMessage<PlayerInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  public ushort ProtoId => ProtocolId.PlayerInfo;
  public string ProtoEnName => "PlayerInfo";
  private static readonly pb::MessageParser<PlayerInfo> _parser = new pb::MessageParser<PlayerInfo>(() => new PlayerInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PlayerInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommonReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerInfo(PlayerInfo other) : this() {
    roleId_ = other.roleId_;
    nick_ = other.nick_;
    sex_ = other.sex_;
    headId_ = other.headId_;
    lv_ = other.lv_;
    gold_ = other.gold_;
    exp_ = other.exp_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerInfo Clone() {
    return new PlayerInfo(this);
  }

  /// <summary>Field number for the "roleId" field.</summary>
  public const int RoleIdFieldNumber = 1;
  private long roleId_;
  /// <summary>
  /// 角色id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long RoleId {
    get { return roleId_; }
    set {
      roleId_ = value;
    }
  }

  /// <summary>Field number for the "nick" field.</summary>
  public const int NickFieldNumber = 2;
  private string nick_ = "";
  /// <summary>
  /// 角色名称
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Nick {
    get { return nick_; }
    set {
      nick_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "sex" field.</summary>
  public const int SexFieldNumber = 3;
  private int sex_;
  /// <summary>
  /// 性别
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Sex {
    get { return sex_; }
    set {
      sex_ = value;
    }
  }

  /// <summary>Field number for the "headId" field.</summary>
  public const int HeadIdFieldNumber = 4;
  private int headId_;
  /// <summary>
  /// 玩家头像id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int HeadId {
    get { return headId_; }
    set {
      headId_ = value;
    }
  }

  /// <summary>Field number for the "lv" field.</summary>
  public const int LvFieldNumber = 5;
  private int lv_;
  /// <summary>
  /// 等级
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Lv {
    get { return lv_; }
    set {
      lv_ = value;
    }
  }

  /// <summary>Field number for the "gold" field.</summary>
  public const int GoldFieldNumber = 6;
  private int gold_;
  /// <summary>
  /// 金币
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Gold {
    get { return gold_; }
    set {
      gold_ = value;
    }
  }

  /// <summary>Field number for the "exp" field.</summary>
  public const int ExpFieldNumber = 7;
  private int exp_;
  /// <summary>
  /// 经验
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Exp {
    get { return exp_; }
    set {
      exp_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PlayerInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PlayerInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RoleId != other.RoleId) return false;
    if (Nick != other.Nick) return false;
    if (Sex != other.Sex) return false;
    if (HeadId != other.HeadId) return false;
    if (Lv != other.Lv) return false;
    if (Gold != other.Gold) return false;
    if (Exp != other.Exp) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (RoleId != 0L) hash ^= RoleId.GetHashCode();
    if (Nick.Length != 0) hash ^= Nick.GetHashCode();
    if (Sex != 0) hash ^= Sex.GetHashCode();
    if (HeadId != 0) hash ^= HeadId.GetHashCode();
    if (Lv != 0) hash ^= Lv.GetHashCode();
    if (Gold != 0) hash ^= Gold.GetHashCode();
    if (Exp != 0) hash ^= Exp.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (RoleId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(RoleId);
    }
    if (Nick.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Nick);
    }
    if (Sex != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Sex);
    }
    if (HeadId != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(HeadId);
    }
    if (Lv != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Lv);
    }
    if (Gold != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(Gold);
    }
    if (Exp != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(Exp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (RoleId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(RoleId);
    }
    if (Nick.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Nick);
    }
    if (Sex != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Sex);
    }
    if (HeadId != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(HeadId);
    }
    if (Lv != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Lv);
    }
    if (Gold != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(Gold);
    }
    if (Exp != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(Exp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (RoleId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(RoleId);
    }
    if (Nick.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Nick);
    }
    if (Sex != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Sex);
    }
    if (HeadId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(HeadId);
    }
    if (Lv != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Lv);
    }
    if (Gold != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gold);
    }
    if (Exp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Exp);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PlayerInfo other) {
    if (other == null) {
      return;
    }
    if (other.RoleId != 0L) {
      RoleId = other.RoleId;
    }
    if (other.Nick.Length != 0) {
      Nick = other.Nick;
    }
    if (other.Sex != 0) {
      Sex = other.Sex;
    }
    if (other.HeadId != 0) {
      HeadId = other.HeadId;
    }
    if (other.Lv != 0) {
      Lv = other.Lv;
    }
    if (other.Gold != 0) {
      Gold = other.Gold;
    }
    if (other.Exp != 0) {
      Exp = other.Exp;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          RoleId = input.ReadInt64();
          break;
        }
        case 18: {
          Nick = input.ReadString();
          break;
        }
        case 24: {
          Sex = input.ReadInt32();
          break;
        }
        case 32: {
          HeadId = input.ReadInt32();
          break;
        }
        case 40: {
          Lv = input.ReadInt32();
          break;
        }
        case 48: {
          Gold = input.ReadInt32();
          break;
        }
        case 56: {
          Exp = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          RoleId = input.ReadInt64();
          break;
        }
        case 18: {
          Nick = input.ReadString();
          break;
        }
        case 24: {
          Sex = input.ReadInt32();
          break;
        }
        case 32: {
          HeadId = input.ReadInt32();
          break;
        }
        case 40: {
          Lv = input.ReadInt32();
          break;
        }
        case 48: {
          Gold = input.ReadInt32();
          break;
        }
        case 56: {
          Exp = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
